### ISSUE TITLE
File bertsquad-12-int8.onnx file is missing

### ISSUE THREAD

**Issue by axelenexis** [EstebanSiravegnaMendix/mlkit-demo#2]
The documentation says:
"Please make sure that the bertsquad-12-int8.onnx file is present in the /path/to/your/app/mlsource/bert folder. You can download it from [here](https://github.com/onnx/models/blob/main/text/machine_comprehension/bert-squad/model/bertsquad-12-int8.onnx) if needed."
But that link does not lead to the file: error 404.

**Comment by axelenexis** [comment]
I found it here: https://github.com/onnx/models/blob/ddbbd1274c8387e3745778705810c340dea3d8c7/validated/text/machine_comprehension/bert-squad/model/bertsquad-12-int8.onnx

**Comment by yunyilmaz** [comment]
Updated link. Thanks for reporting
